/**
 * 来自·默檐 -  2026 默檐
 * 2026/9/8 14:10
 *
 * 免责声明:本项目仅供学习、交流与合法用途,开发者本意不在于造成任何不良影响。
 * 使用者应遵守适用法律法规,并自行承担因不当使用所产生的责任。
 */
 #pragma once

namespace ytbl {

inline const char* const kGlassVertexShader =
    "#version 300 es\n"
    "precision highp float;\n"
    "in vec2 aPos;\n"
    "in vec2 aCoord;\n"
    "out vec2 vCoord;\n"
    "void main() {\n"
    "    gl_Position = vec4(aPos, 0.0, 1.0);\n"
    "    vCoord = aCoord;\n"
    "}\n";

inline const char* const kGlassFragmentShader =
    "#version 300 es\n"
    "precision highp float;\n"
    "#define float2 vec2\n"
    "#define float3 vec3\n"
    "#define float4 vec4\n"
    "#define half float\n"
    "#define half2 vec2\n"
    "#define half3 vec3\n"
    "#define half4 vec4\n"
    "in vec2 vCoord;\n"
    "out vec4 fragColor;\n"
    "uniform sampler2D uContent;\n"
    "uniform vec2 uSize;\n"
    "uniform vec2 uCaptureOriginOffset;\n"
    "uniform vec2 uCaptureSize;\n"
    "uniform vec2 uCaptureTextureSize;\n"
    "uniform float uBackdropScaleX;\n"
    "uniform float uBackdropScaleY;\n"
    "uniform float uBackdropMix;\n"
    "uniform vec4 uCornerRadii;\n"
    "uniform float uRefractionHeight;\n"
    "uniform float uRefractionAmount;\n"
    "uniform float uDepthEffect;\n"
    "uniform float uDispersion;\n"
    "uniform float uBlurRadius;\n"
    "uniform float uOpacity;\n"
    "uniform vec3 uColorCtrl;\n"
    "uniform float uVibrancy;\n"
    "uniform vec4 uSurfaceColor;\n"
    "uniform float uTintMode;\n"
    "uniform float uHighlightMode;\n"
    "uniform vec4 uHighlightColor;\n"
    "uniform float uHighlightColorAlpha;\n"
    "uniform float uHighlightAngle;\n"
    "uniform float uHighlightFalloff;\n"
    "uniform float uHighlightAlpha;\n"
    "uniform float uHighlightWidth;\n"
    "uniform float uHighlightBlur;\n"
    "uniform float uUseTexture;\n"
    "uniform float uOpaque;\n"
    "uniform vec4 uFallback;\n"
    "uniform vec4 uInnerShadowColor;\n"
    "uniform vec2 uInnerShadowOffset;\n"
    "uniform float uInnerShadowRadius;\n"
    "uniform float uInnerShadowAlpha;\n"
    "uniform float uIHMode;\n"
    "uniform vec2 uIHPosition;\n"
    "uniform float uIHRadius;\n"
    "uniform float uIHAlpha;\n"
    "\n"
    "float radiusAt(vec2 coord, vec4 radii) {\n"
    "    if (coord.x >= 0.0) return coord.y <= 0.0 ? radii.y : radii.z;\n"
    "    return coord.y <= 0.0 ? radii.x : radii.w;\n"
    "}\n"
    "float sdRoundedRect(vec2 coord, vec2 halfSize, float radius) {\n"
    "    vec2 cornerCoord = abs(coord) - (halfSize - vec2(radius));\n"
    "    float outside = length(max(cornerCoord, vec2(0.0))) - radius;\n"
    "    float inside = min(max(cornerCoord.x, cornerCoord.y), 0.0);\n"
    "    return outside + inside;\n"
    "}\n"
    "vec2 gradSdRoundedRect(vec2 coord, vec2 halfSize, float radius) {\n"
    "    vec2 cornerCoord = abs(coord) - (halfSize - vec2(radius));\n"
    "    if (cornerCoord.x >= 0.0 || cornerCoord.y >= 0.0) {\n"
    "        vec2 g = max(cornerCoord, vec2(0.0));\n"
    "        float gl = length(g);\n"
    "        return sign(coord) * (gl > 0.0001 ? g / gl : vec2(0.0));\n"
    "    }\n"
    "    float gradX = step(cornerCoord.y, cornerCoord.x);\n"
    "    return sign(coord) * vec2(gradX, 1.0 - gradX);\n"
    "}\n"
    "float circleMap(float x) {\n"
    "    float safeX = clamp(x, 0.0, 1.0);\n"
    "    return 1.0 - sqrt(max(1.0 - safeX * safeX, 0.0));\n"
    "}\n"
    "vec2 safeNormalize(vec2 v) {\n"
    "    float len = length(v);\n"
    "    return len > 0.0001 ? v / len : vec2(0.0);\n"
    "}\n"
    "vec2 contentUv(vec2 pixel) {\n"
    "    vec2 storage = max(uCaptureTextureSize, vec2(1.0));\n"
    "\n"
    "\n"
    "\n"
    "    vec2 valid = max((uCaptureSize - vec2(0.5)) / storage, vec2(0.0));\n"
    "    vec2 uv = vec2(pixel.x / storage.x, (uCaptureSize.y - pixel.y) / storage.y);\n"
    "    return clamp(uv, vec2(0.0), valid);\n"
    "}\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "vec4 backdropSample(vec2 pixel) {\n"
    "    vec4 c = texture(uContent, contentUv(pixel));\n"
    "    float fbA = clamp(c.a, 0.0, 1.0);\n"
    "    c.rgb += uFallback.rgb * uFallback.a * (1.0 - fbA);\n"
    "    c.a = fbA + uFallback.a * (1.0 - fbA);\n"
    "    return c;\n"
    "}\n"
    "vec4 sampleContent(vec2 coord) {\n"
    "    vec2 pixel = coord + uCaptureOriginOffset;\n"
    "    vec4 base = backdropSample(pixel);\n"
    "    float mixAmount = clamp(uBackdropMix, 0.0, 1.0);\n"
    "    if (mixAmount <= 0.0) return base;\n"
    "    vec2 scale = vec2(uBackdropScaleX, uBackdropScaleY);\n"
    "    if (scale.x <= 0.001 || scale.y <= 0.001) return base;\n"
    "    vec2 center = uCaptureSize * 0.5;\n"
    "    vec2 transformedPixel = center + (pixel - center) / scale;\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "    vec4 layer = backdropSample(transformedPixel) * mixAmount;\n"
    "    return layer + base * (1.0 - layer.a);\n"
    "}\n"
    "vec4 blurContent(vec2 coord, float radius) {\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "    if (uUseTexture < 0.5) return uFallback;\n"
    "    vec4 c;\n"
    "    if (radius <= 0.5) {\n"
    "        c = sampleContent(coord);\n"
    "    } else {\n"
    "        float stepSize = radius * 0.5;\n"
    "        vec2 diag = vec2(stepSize) * 0.7;\n"
    "        c = sampleContent(coord);\n"
    "        c += sampleContent(coord + vec2(stepSize, 0.0));\n"
    "        c += sampleContent(coord - vec2(stepSize, 0.0));\n"
    "        c += sampleContent(coord + vec2(0.0, stepSize));\n"
    "        c += sampleContent(coord - vec2(0.0, stepSize));\n"
    "        c += sampleContent(coord + diag);\n"
    "        c += sampleContent(coord + vec2(diag.x, -diag.y));\n"
    "        c += sampleContent(coord + vec2(-diag.x, diag.y));\n"
    "        c += sampleContent(coord - diag);\n"
    "        c /= 9.0;\n"
    "    }\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "    if (c.a <= 0.001) return vec4(0.0);\n"
    "    c.rgb = clamp(c.rgb / c.a, 0.0, 1.0);\n"
    "\n"
    "\n"
    "    if (uOpaque > 0.5 && c.a > 0.001) c.a = 1.0;\n"
    "    return c;\n"
    "}\n"
    "vec3 applyColorControls(vec3 c, vec3 bcs) {\n"
    "    float brightness = bcs.x;\n"
    "    float contrast = bcs.y;\n"
    "    float saturation = bcs.z;\n"
    "    float invSat = 1.0 - saturation;\n"
    "    vec3 lum = vec3(0.213, 0.715, 0.072) * invSat;\n"
    "    float t = 0.5 - contrast * 0.5 + brightness;\n"
    "    return vec3(dot(c, contrast * (lum + vec3(saturation, 0.0, 0.0))) + t,\n"
    "                dot(c, contrast * (lum + vec3(0.0, saturation, 0.0))) + t,\n"
    "                dot(c, contrast * (lum + vec3(0.0, 0.0, saturation))) + t);\n"
    "}\n"
    "void main() {\n"
    "    vec2 halfSize = uSize * 0.5;\n"
    "    vec2 centeredCoord = vCoord - halfSize;\n"
    "    float radius = radiusAt(centeredCoord, uCornerRadii);\n"
    "    float sd = sdRoundedRect(centeredCoord, halfSize, radius);\n"
    "    vec2 contentCoord = vCoord;\n"
    "    float dispersion = uDispersion;\n"
    "    if (-sd < uRefractionHeight && uRefractionHeight > 0.0001 && uRefractionAmount > 0.0) {\n"
    "        float sdC = min(sd, 0.0);\n"
    "        float d = circleMap(1.0 - (-sdC / uRefractionHeight)) * (-uRefractionAmount);\n"
    "        float gradRadius = min(radius * 1.5, min(halfSize.x, halfSize.y));\n"
    "        vec2 grad = safeNormalize(gradSdRoundedRect(centeredCoord, halfSize, gradRadius)\n"
    "                       + uDepthEffect * safeNormalize(centeredCoord));\n"
    "        contentCoord = vCoord + d * grad;\n"
    "    } else if (uRefractionAmount > 0.0) {\n"
    "        dispersion = 0.0;\n"
    "    }\n"
    "    vec4 color;\n"
    "    if (dispersion > 0.0 && uRefractionHeight > 0.0001 && uRefractionAmount > 0.0) {\n"
    "        float sdC = min(sd, 0.0);\n"
    "        float d = circleMap(1.0 - (-sdC / uRefractionHeight)) * (-uRefractionAmount);\n"
    "        float gradRadius = min(radius * 1.5, min(halfSize.x, halfSize.y));\n"
    "        vec2 grad = safeNormalize(gradSdRoundedRect(centeredCoord, halfSize, gradRadius)\n"
    "                       + uDepthEffect * safeNormalize(centeredCoord));\n"
    "        vec2 refractedCoord = vCoord + d * grad;\n"
    "        float edgeX = abs(centeredCoord.x / max(halfSize.x, 0.001));\n"
    "        float edgeY = abs(centeredCoord.y / max(halfSize.y, 0.001));\n"
    "        float dispersionIntensity = dispersion * clamp(edgeX * edgeY, 0.0, 1.0);\n"
    "        vec2 dispersedCoord = d * grad * dispersionIntensity;\n"
    "        color = vec4(0.0);\n"
    "        vec4 red = blurContent(refractedCoord + dispersedCoord, uBlurRadius);\n"
    "        color.r += red.r / 3.5; color.a += red.a / 7.0;\n"
    "        vec4 orange = blurContent(refractedCoord + dispersedCoord * (2.0 / 3.0), uBlurRadius);\n"
    "        color.r += orange.r / 3.5; color.g += orange.g / 7.0; color.a += orange.a / 7.0;\n"
    "        vec4 yellow = blurContent(refractedCoord + dispersedCoord * (1.0 / 3.0), uBlurRadius);\n"
    "        color.r += yellow.r / 3.5; color.g += yellow.g / 3.5; color.a += yellow.a / 7.0;\n"
    "        vec4 green = blurContent(refractedCoord, uBlurRadius);\n"
    "        color.g += green.g / 3.5; color.a += green.a / 7.0;\n"
    "        vec4 cyan = blurContent(refractedCoord - dispersedCoord * (1.0 / 3.0), uBlurRadius);\n"
    "        color.g += cyan.g / 3.5; color.b += cyan.b / 3.0; color.a += cyan.a / 7.0;\n"
    "        vec4 blue = blurContent(refractedCoord - dispersedCoord * (2.0 / 3.0), uBlurRadius);\n"
    "        color.b += blue.b / 3.0; color.a += blue.a / 7.0;\n"
    "        vec4 purple = blurContent(refractedCoord - dispersedCoord, uBlurRadius);\n"
    "        color.r += purple.r / 7.0; color.b += purple.b / 3.0; color.a += purple.a / 7.0;\n"
    "        color.a = clamp(color.a, 0.0, 1.0);\n"
    "    } else {\n"
    "        color = blurContent(contentCoord, uBlurRadius);\n"
    "    }\n"
    "    vec3 bcs = uColorCtrl;\n"
    "    if (uVibrancy > 0.5) bcs.z *= 1.5;\n"
    "    color.rgb = applyColorControls(color.rgb, bcs);\n"
    "    color.a *= uOpacity;\n"
    "    if (uTintMode > 1.5) {\n"
    "        color = vec4(mix(color.rgb, uSurfaceColor.rgb, uSurfaceColor.a),\n"
    "                     color.a + uSurfaceColor.a * (1.0 - color.a));\n"
    "    } else if (uTintMode > 0.5) {\n"
    "        float luma = dot(color.rgb, vec3(0.213, 0.715, 0.072));\n"
    "        vec3 hue = uSurfaceColor.rgb * (0.35 + 1.3 * luma);\n"
    "        color.rgb = mix(color.rgb, hue, 0.75 * uSurfaceColor.a);\n"
    "        color.a = max(color.a, 0.75 * uSurfaceColor.a);\n"
    "    }\n"
    "    if (uHighlightMode > 0.5) {\n"
    "        float gradRadius = min(radius * 1.5, min(halfSize.x, halfSize.y));\n"
    "        vec2 grad = gradSdRoundedRect(centeredCoord, halfSize, gradRadius);\n"
    "        float edgeDistance = abs(sd);\n"
    "        float edgeBand = 1.0 - smoothstep(max(uHighlightWidth - uHighlightBlur, 0.0),\n"
    "                                           uHighlightWidth + uHighlightBlur, edgeDistance);\n"
    "        float d = dot(grad, vec2(cos(uHighlightAngle), sin(uHighlightAngle)));\n"
    "        float intensity = pow(abs(d), max(uHighlightFalloff, 0.001));\n"
    "        if (uHighlightMode > 2.5) {\n"
    "            float ha = uHighlightAlpha * uHighlightColorAlpha * edgeBand;\n"
    "            color.rgb += uHighlightColor.rgb * ha; color.a = clamp(color.a + ha, 0.0, 1.0);\n"
    "        } else if (uHighlightMode > 1.5) {\n"
    "            float ha = intensity * edgeBand * uHighlightAlpha * step(0.0, d);\n"
    "            color.rgb = mix(color.rgb, vec3(1.0), ha); color.a += ha * (1.0 - color.a);\n"
    "        } else {\n"
    "            float ha = intensity * edgeBand * uHighlightAlpha;\n"
    "            color.rgb += uHighlightColor.rgb * ha; color.a = clamp(color.a + ha, 0.0, 1.0);\n"
    "        }\n"
    "    }\n"
    "    if (uInnerShadowAlpha > 0.001) {\n"
    "        vec2 offCoord = centeredCoord - uInnerShadowOffset;\n"
    "        float isd = sdRoundedRect(offCoord, halfSize, radius);\n"
    "        float mask = clamp(isd / max(uInnerShadowRadius, 1.0), 0.0, 1.0);\n"
    "        float inside = clamp(0.5 - sd, 0.0, 1.0);\n"
    "        float sa = mask * inside * uInnerShadowAlpha;\n"
    "        color.rgb = mix(color.rgb, uInnerShadowColor.rgb, sa);\n"
    "        color.a += sa * (1.0 - color.a);\n"
    "    }\n"
    "    if (uIHMode > 0.5 && uIHAlpha > 0.001) {\n"
    "        float p = uIHAlpha;\n"
    "        float spot = smoothstep(uIHRadius, uIHRadius * 0.5, distance(vCoord, uIHPosition));\n"
    "        color.rgb += vec3(0.08 * p + 0.15 * p * spot);\n"
    "        color.a = clamp(color.a + 0.08 * p + 0.15 * p * spot, 0.0, 1.0);\n"
    "    }\n"
    "\n"
    "\n"
    "    float edgeWidth = max(fwidth(sd), 0.75);\n"
    "    color.a *= 1.0 - smoothstep(0.0, edgeWidth, sd);\n"
    "    fragColor = color;\n"
    "}\n";

}
